name: Build and Push to DockerHub

on: [ "workflow_dispatch", "push" ]
permissions:
      id-token: write
      contents: read
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Docker build
        run: docker build -t gha-image:latest .

      - name: Taging a Docker image
        run: |
          docker tag gha-image:latest hemanth12reddy/git-hub-actions:$GITHUB_RUN_NUMBER
          
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker push
        run: docker push hemanth12reddy/git-hub-actions:$GITHUB_RUN_NUMBER



