name: main

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Docker Version
        run: docker version
      # - name: Docker Login
      #   uses: docker/login-action@v3.0.0
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Docker build and push
      #   uses: cloudposse/github-action-docker-build-push@1.14.0
      
      # - name: Docker build and push
      #   uses: cloudposse/github-action-docker-build-push@1.14.0
        
