name: main

on: [ "workflow_dispatch", "push" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4.1.1
      
      # - name: Docker build
      #   run: docker build -t gha-image:latest .

      # - name: Taging a Docker image
      #   run: |
      #     docker tag gha-image:latest hemanth12reddy/git-hub-actions:$GITHUB_RUN_NUMBER
          
      # - name: Docker Login
      #   uses: docker/login-action@v3.0.0
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Docker push
      #   run: docker push hemanth12reddy/git-hub-actions:$GITHUB_RUN_NUMBER
          
      - name: Get External IP
        run: |
          IP=$(curl http://myexternalip.com/raw | tail -n 1 | cut -d' ' -f4)
          echo "The IP address is: $IP"
          echo "::set-env name=IP::${IP}"  # Use new variable in set-env
      
      - name: Something
        env:
          IP: ${{ steps.Get-External-IP.outputs.IP }}
        run: |
          echo "my ip is $IP from last step"
